# This is a basic workflow that is manually triggered

name: Release Bot Projects

on:
  create:
    tags:
      - 0.0.*
jobs:
  # This workflow contains a single job called "greet"
  allinone:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
 
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
        
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      
    - name: Checkout Latest Tag
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ steps.previoustag.outputs.tag }}
    
    - name: Zip JavaScript Project
      run: zip -r bot_JavaScript_default_${{ steps.previoustag.outputs.tag }}.zip ./bot/js/*
      
    - name: Zip TypeScript Project
      run: zip -r bot_TypeScript_default_${{ steps.previoustag.outputs.tag }}.zip ./bot/ts/*
      
    - name: Zip CSharp Project
      run: zip -r bot_CSharp_default_${{ steps.previoustag.outputs.tag }}.zip ./bot/csharp/*
      
    - name: Create Release
      uses: ncipollo/release-action@v1.7.3
      with:
        artifacts: ./*.zip, manifest.json
        name: "test"
        token: ${{ secrets.GITHUB_TOKEN }}
