# This is a basic workflow that is manually triggered

name: Release Bot Projects

on:
  create:
    tags:
      - 0.0.*
jobs:
  # This workflow contains a single job called "greet"
  allinone:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: Get Latest Tag
      uses: oprypin/find-latest-tag@v1
      id: latest

    - name: Checkout Latest Tag
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ steps.latest.outputs.tag }}
    
    - name: Zip JavaScript Project
      run: zip -r bot_JavaScript_default_0.1.0.zip ./bot/js/*
      
    - name: Zip TypeScript Project
      run: zip -r bot_TypeScript_default_0.1.0.zip ./bot/ts/*
      
    - name: Zip CSharp Project
      run: zip -r bot_CSharp_default_0.1.0.zip ./bot/csharp/*
      
    - name: Create Release
      uses: ncipollo/release-action@v1.7.3
      with:
        artifacts: ./*.zip, manifest.json
        name: "test"
        token: ${{ secrets.GITHUB_TOKEN }}
